lib/fd_web/router.ex
defmodule FdWeb.Router do
  use FdWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", FdWeb do
    pipe_through :browser_auth # Use the default browser stack
    # Manage
    get "/manage", ManageController, :index, as: :manage
    get "/:instance_id/manage", ManageController, :show, as: :manage
    put "/:instance_id/manage", ManageController, :update, as: :manage
    get "/manage/logout", ManageController, :logout
    post "/manage/login", ManageController, :send_token, as: :manage
    get "/manage/login/:token", ManageController, :login_by_token, as: :manage
    get "/tools/nodeinfo", Tools.NodeinfoController, :index, as: :nodeinfo_tool
    post "/tools/nodeinfo", Tools.NodeinfoController, :post, as: :nodeinfo_tool
    get "/tools/nodeinfo/:hostname", Tools.NodeinfoController, :show, as: :nodeinfo_tool
  end

  scope "/", FdWeb do
    pipe_through :browser # Use the default browser stack

    get "/info", PageController, :show
    get "/about", PageController, :show
    get "/about/*slug", PageController, :show
    get "/api/*slug", PageController, :show
    get "/monitoring", PageController, :show
    get "/stats", PageController, :stats

    # Define /pleroma, /mastodon, …
    for s <- Fd.ServerName.list_names do
      get Fd.ServerName.route_path(s), InstanceController, :index, as: :instance_sserver
      get Fd.ServerName.route_path(s) <> "/versions", ServerController, as: :server_sversions
    end

    get "/servers", ServerController, :index

    get "/all", InstanceController, :index, as: :instance_all
    get "/down", InstanceController, :index, as: :instance_down
    get "/newest", InstanceController, :index, as: :instance_newest
    get "/oldest", InstanceController, :index, as: :instance_oldest
    get "/closed", InstanceController, :index, as: :instance_closed
    get "/checks", CheckController, :index, as: :latest_checks
    get "/tld", InstanceController, :tld, as: :instance
    get "/tld/:tld", InstanceController, :index, as: :instance_tld
    get "/domain", InstanceController, :domain, as: :instance
    get "/domain/:domain", InstanceController, :index, as: :instance_domain
    get "/t", InstanceController, :tags, as: :topics
    get "/t/:tag", InstanceController, :index, as: :instance_tag

    get "/hosts", HostController, :index, as: :host

    get "/reports", ReportController, :index
    get "/reports/:report", ReportController, :show


    @traps ~w(wp-login.php)
    for trap <- @traps do
      get "/#{trap}", PageController, :trap
    end

    @notfound ~w(statistics.json siteinfo.json poco)
    for notfound <- @notfound do
      get "/#{notfound}", PageController, :not_found
    end


    resources "/", InstanceController, only: [:index, :show] do
      get "/nodeinfo", InstanceController, :nodeinfo
      get "/stats", InstanceController, :stats
      get "/stats/:interval", InstanceController, :stats
      get "/emojis", InstanceController, :emojis
      get "/peers", InstanceController, :peers
      get "/federation", InstanceController, :federation
      get "/timeline", InstanceController, :timeline
      get "/public_timeline", InstanceController, :public_timeline
      get "/score", InstanceController, :score
      get "/checks", InstanceController, :checks
      get "/checks/:from_time", CheckController, :show, as: :check
      get "/checks/:from_time/:to_time", CheckController, :show, as: :check
      get "/chart/:name", InstanceChartController, :show, as: :chart
    end

    #resources "/tags", TagController

    # This route will mostly never be directly hit (eaten by instance /:id) but this is for route helpers
    # Real routes are generated per-server by Fd.ServerName.list_names a couple of lines before
    get "/:server", InstanceController, :index, as: :instance_server
    get "/:server/versions", ServerController, :versions, as: :server_versions
  end


  if Mix.env == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end

  scope "/api", FdWeb.Api do
    pipe_through :api
    get "/v1/stats", GlobalStatsController, :index
    get "/v1/stats/server/:server_name", GlobalStatsController, :server
    get "/v1/stats/isps", GlobalStatsController, :isps
    get "/v1/stats/countries", GlobalStatsController, :countries
  end
end

lib/fd_web/controllers/check_controller.ex
defmodule FdWeb.CheckController do
  use FdWeb, :controller

  alias Fd.Repo
  alias Fd.Instances
  alias Fd.Instances.{InstanceCheck}
  import Ecto.Query, warn: false

  def index(conn, params) do
    checks = from(c in InstanceCheck, limit: 500, order_by: [desc: c.updated_at])
    checks = Enum.reduce(params, checks, &check_filter_reduce/2)

    checks = checks
    |> Repo.all
    |> Repo.preload(:instance)
    conn
    |> assign(:title, "Latest Checks")
    |> render("index.html", checks: checks)
  end

  def show(conn, params = %{"instance_id" => id, "from_time" => from_time_iso}) do
    instance = Instances.get_instance_by_domain!(id)
    iid = instance.id
    to_time_iso = Map.get(params, "to_time", from_time_iso)
    from_time = NaiveDateTime.from_iso8601!(from_time_iso)
    to_time = NaiveDateTime.from_iso8601!(to_time_iso)
    range? = !(from_time_iso == to_time_iso)
    checks = from(c in InstanceCheck,
      where: c.instance_id == ^iid and c.updated_at >= ^from_time and c.updated_at <= ^to_time,
      order_by: [asc: c.updated_at]
    )
    |> Repo.all
    title = if range?, do: "from #{from_time} to #{to_time}", else: "at #{from_time}"
    conn
    |> assign(:section, "checks")
    |> assign(:title, "Checks on #{instance.domain} #{title}")
    |> assign(:private, Instances.Instance.hidden?(instance))
    |> render("show.html", checks: checks, instance: instance, range?: range?, from_time: from_time, to_time: to_time)
  end

  defp check_filter_reduce({"error", error}, query) do
    where(query, [c], c.error_s == ^error)
  end
  defp check_filter_reduce(_, query), do: query

end

lib/fd_web/views/check_view.ex
defmodule FdWeb.CheckView do
  use FdWeb, :view

end

lib/fd_web/templates/check/index.html.eex
<h2>latest checks</h2>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>instance</th>
      <th>time</th>
      <th>server</th>
      <th>signup</th>
      <th>users</th>
      <th>statuses</th>
      <th>peers</th>
      <th>emojis</th>
    </tr>
  </thead>
  <tbody>
    <%= for check <- @checks do %>
      <tr>
        <td><span class="badge badge-up-<%= to_string(check.up) %>">&nbsp;</span></td>
        <td>
          <%= if Fd.Instances.Instance.hidden?(check.instance) do %>
            <i class="text-muted">private</i>
          <% else %>
            <%= link FdWeb.InstanceView.name(check.instance), to: instance_path(@conn, :show, check.instance) %>
          <% end %>
          <%= if check.instance.dead, do: content_tag(:sup, "☨") %>
          <%= if check.instance.monitor, do: content_tag(:sup, raw("&#128065;")) %>
        </td>
        <td>
          <%= if Fd.Instances.Instance.hidden?(check.instance) do %>
            <%= link format_date(check.updated_at, "normal"), to: instance_check_path(@conn, :show, check.instance, NaiveDateTime.to_iso8601(check.updated_at)) %>
          <% else %>
            <%= format_date(check.updated_at, "normal") %>
          <% end %>
        </td>
        <%= if check.error_s do %>
          <td colspan=6><span class="text-danger"><%= check.error_s %></span></td>
        <% else %>
          <td><%= Fd.ServerName.from_int(check.instance.server) %> <%= check.version %></td>
          <td><%= check.signup %></td>
          <td><%= check.users %></td>
          <td><%= check.statuses %></td>
          <td><%= check.peers %></td>
          <td><%= check.emojis %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

lib/fd_web/templates/check/show.html.eex
<%= FdWeb.InstanceView.render "_header.html", conn: @conn, instance: @instance %>

<div class="panel panel-default">
  <%= if @range? do %>
    <div class="panel-heading">
      <%= Enum.count(@checks) %> checks from <%= @from_time %> to <%= @to_time %>.
    </div>
  <% end %>
<table class="table table-condensed">
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>time</th>
      <th>users</th>
      <th>statuses</th>
      <th>peers</th>
      <th>emojis</th>
      <th>version</th>
      <th>signup</th>
    </tr>
  </thead>
  <tbody>
    <%= for check <- @checks do %>
      <tr>
        <td><span class="badge badge-up-<%= to_string(check.up) %>">&nbsp;</span></td>
        <td><%= link format_date(check.updated_at, "normal"), to: instance_check_path(@conn, :show, @instance, NaiveDateTime.to_iso8601(check.updated_at)) %></td>
        <%= if check.error_s do %>
          <td colspan=6><strong class="text-danger"><%= check.error_s %></strong></td>
        <% else %>
          <td><%= check.users %></td>
          <td><%= check.statuses %></td>
          <td><%= check.peers %></td>
          <td><%= check.emojis %></td>
          <td><%= check.version %></td>
          <td><%= check.signup %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>