lib/fd_web/router.ex
defmodule FdWeb.Router do
  use FdWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", FdWeb do
    pipe_through :browser_auth # Use the default browser stack
    # Manage
    get "/manage", ManageController, :index, as: :manage
    get "/:instance_id/manage", ManageController, :show, as: :manage
    put "/:instance_id/manage", ManageController, :update, as: :manage
    get "/manage/logout", ManageController, :logout
    post "/manage/login", ManageController, :send_token, as: :manage
    get "/manage/login/:token", ManageController, :login_by_token, as: :manage
    get "/tools/nodeinfo", Tools.NodeinfoController, :index, as: :nodeinfo_tool
    post "/tools/nodeinfo", Tools.NodeinfoController, :post, as: :nodeinfo_tool
    get "/tools/nodeinfo/:hostname", Tools.NodeinfoController, :show, as: :nodeinfo_tool
  end

  scope "/", FdWeb do
    pipe_through :browser # Use the default browser stack

    get "/info", PageController, :show
    get "/about", PageController, :show
    get "/about/*slug", PageController, :show
    get "/api/*slug", PageController, :show
    get "/monitoring", PageController, :show
    get "/stats", PageController, :stats

    # Define /pleroma, /mastodon, …
    for s <- Fd.ServerName.list_names do
      get Fd.ServerName.route_path(s), InstanceController, :index, as: :instance_sserver
      get Fd.ServerName.route_path(s) <> "/versions", ServerController, as: :server_sversions
    end

    get "/servers", ServerController, :index

    get "/all", InstanceController, :index, as: :instance_all
    get "/down", InstanceController, :index, as: :instance_down
    get "/newest", InstanceController, :index, as: :instance_newest
    get "/oldest", InstanceController, :index, as: :instance_oldest
    get "/closed", InstanceController, :index, as: :instance_closed
    get "/checks", CheckController, :index, as: :latest_checks
    get "/tld", InstanceController, :tld, as: :instance
    get "/tld/:tld", InstanceController, :index, as: :instance_tld
    get "/domain", InstanceController, :domain, as: :instance
    get "/domain/:domain", InstanceController, :index, as: :instance_domain
    get "/t", InstanceController, :tags, as: :topics
    get "/t/:tag", InstanceController, :index, as: :instance_tag

    get "/hosts", HostController, :index, as: :host

    get "/reports", ReportController, :index
    get "/reports/:report", ReportController, :show


    @traps ~w(wp-login.php)
    for trap <- @traps do
      get "/#{trap}", PageController, :trap
    end

    @notfound ~w(statistics.json siteinfo.json poco)
    for notfound <- @notfound do
      get "/#{notfound}", PageController, :not_found
    end


    resources "/", InstanceController, only: [:index, :show] do
      get "/nodeinfo", InstanceController, :nodeinfo
      get "/stats", InstanceController, :stats
      get "/stats/:interval", InstanceController, :stats
      get "/emojis", InstanceController, :emojis
      get "/peers", InstanceController, :peers
      get "/federation", InstanceController, :federation
      get "/timeline", InstanceController, :timeline
      get "/public_timeline", InstanceController, :public_timeline
      get "/score", InstanceController, :score
      get "/checks", InstanceController, :checks
      get "/checks/:from_time", CheckController, :show, as: :check
      get "/checks/:from_time/:to_time", CheckController, :show, as: :check
      get "/chart/:name", InstanceChartController, :show, as: :chart
    end

    #resources "/tags", TagController

    # This route will mostly never be directly hit (eaten by instance /:id) but this is for route helpers
    # Real routes are generated per-server by Fd.ServerName.list_names a couple of lines before
    get "/:server", InstanceController, :index, as: :instance_server
    get "/:server/versions", ServerController, :versions, as: :server_versions
  end


  if Mix.env == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end

  scope "/api", FdWeb.Api do
    pipe_through :api
    get "/v1/stats", GlobalStatsController, :index
    get "/v1/stats/server/:server_name", GlobalStatsController, :server
    get "/v1/stats/isps", GlobalStatsController, :isps
    get "/v1/stats/countries", GlobalStatsController, :countries
  end
end

lib/fd_web/controllers/report_controller.ex
defmodule FdWeb.ReportController do
  use FdWeb, :controller

  alias Fd.Stats

  @reports %{
    "2018" => {"🎉 2018 Report", %{"from" => "2018-04-30", "to" => "2018-12-31"}},
    "2019-01" => {"January 2019 Report", %{"from" => "2019-01-01", "to" => "2019-01-31"}},
    "2019-02" => {"February 2019 Report", %{"from" => "2019-02-01", "to" => "2019-02-28"}},
    "2019-03" => {"March 2019 Report", %{"from" => "2019-03-01", "to" => "2019-03-31"}},
    "2019-04" => {"April 2019 Report", %{"from" => "2019-04-01", "to" => "2019-04-30"}},
    "2019-05" => {"May 2019 Report", %{"from" => "2019-05-01", "to" => "2019-05-31"}},
  }

  def index(conn, _) do
    conn
    |> assign(:title, "Reports")
    |> render("index.html", reports: Enum.reverse(@reports))
  end

  for {key, {title, options}} <- @reports do
    def show(conn, %{"report" => unquote(key)}) do
      stats = Stats.file_evolution(unquote(Macro.escape(options)))

      conn
      |> assign(:title, unquote(title))
      |> render("show.html", [
        stats: stats,
        name: unquote(key)
      ])
    end
  end

end

lib/fd_web/views/report_view.ex
defmodule FdWeb.ReportView do
  use FdWeb, :view

  def percentage(title, first, last) do
    diff = last - first
    percentage = ((diff / first) * 100)
                 |> Float.ceil()
                 |> trunc()

    percent_str = if percentage > 0 do
      "+#{percentage}%"
    else
      "#{percentage}%"
    end

    [
      content_tag(:span, [percent_str], style: "font-weight: bold; font-size: 110%;"),
      raw("&nbsp;"),
      title,
      raw("&nbsp;"),
      content_tag(:span, [number(diff, plus: true)], style: "font-size: 80%")
    ]
  end

end

lib/fd_web/templates/report/index.html.eex
<h1>Reports</h1>

<ul>
<%= for {period, {title, _}} <- @reports do %>
  <li><%= link title, to: report_path(@conn, :show, period) %></li>
<% end %>
</ul>

lib/fd_web/templates/report/show.html.eex
<h1>🎉 <%= @name %> 🎉</h1>

<style type="text/css">
p.lead strong, p.lead b { font-weight: bold }
</style>

<div class="row">
  <div class="col">
<p class="lead">
  <span class="text-muted">
    From <%= format_date(@stats.query.from) %> to <%= format_date(@stats.query.to) %>,
  </span>
  <br />

  the reachable fediverse grew

  <br />

  from <b><%= number(get_in(@stats, [:network, :previous, :instances])) %></b>
    instances
    to <b><%= number(get_in(@stats, [:network, :all, :instances])) %></b>

  <br />

  from <b><%= number(get_in(@stats, [:network, :users_first])) %></b>
  users
  to <b><%= number(get_in(@stats, [:network, :users_last])) %></b>

  <br />

  and from <b><%= number(get_in(@stats, [:network, :statuses_first])) %></b>
  statuses
  to <b><%= number(get_in(@stats, [:network, :statuses_last])) %></b>
</p>
</div>

<div class="col">
  <p class="lead">
  <br />
  <%= percentage("instances", get_in(@stats, [:network, :previous, :instances]), get_in(@stats, [:network, :all, :instances])) %>
  <br />
  <%= percentage("users", get_in(@stats, [:network, :users_first]), get_in(@stats, [:network, :users_last])) %>
  <br />
  <%= percentage("statuses", get_in(@stats, [:network, :statuses_first]), get_in(@stats, [:network, :statuses_last])) %>
  </p>
</div>

</div>

<p class="lead">
  <br /><br />

  <span class="text-muted">In this period,</span>
  <br />
  <strong><%= number(get_in(@stats, [:network, :instances])) %> new instances</strong> joined the fediverse,
  <strong><%= number(get_in(@stats, [:network, :users])) %> users signed up</strong> and <strong>wrote <%= number(get_in(@stats, [:network, :statuses])) %> statuses</strong>
  <br />
  while <strong><%= number(get_in(@stats, [:network, :dead, :instances])) %> instances became down</strong>, <strong>removing</strong> <%= number(get_in(@stats, [:network, :dead, :users_first])) %> users
  and <%= number(get_in(@stats, [:network, :dead, :statuses_first])) %> statuses.
</p>

<br />
<br />

<h2 id="servers">
  Servers
</h2>
<br />

<div class="row">
  <% stats = Enum.map(@stats.servers, fn(stat) ->
    Map.merge(stat, Fd.ServerName.data(stat.server||0))
end)
  |> Enum.filter(fn(stat) ->
stat && Map.get(stat, :name) && !Map.get(stat, :hidden, false) && Map.get(stat, :instances) && ((Map.get(stat, :instances) - (Map.get(stat, :dead_instances)||0)) > 2)
  end)
  |> Enum.with_index()
%>

<% neg = Enum.map(@stats.servers, fn(stat) ->
    Map.merge(stat, Fd.ServerName.data(stat.server||0))
end)
  |> Enum.filter(fn(stat) ->
stat && Map.get(stat, :name) && !Map.get(stat, :hidden, false) && Map.get(stat, :instances) && ((Map.get(stat, :instances) - (Map.get(stat, :dead_instances)||0)) < 0)
  end)
  |> Enum.with_index()
%>

  <% new = Enum.map(@stats.servers, fn(stat) ->
    Map.merge(stat, Fd.ServerName.data(stat.server||0))
end)
  |> Enum.filter(fn(stat) ->
stat && Map.get(stat, :name) && !Map.get(stat, :hidden, false) && Map.get(stat, :instances) && ((Map.get(stat, :instances)) > 1)
  end)
  |> Enum.with_index()
%>
  <%= for {stat, id} <- stats do %>

    <div class="col-sm-4">
      <h3 id="server-<%= stat.slug %>">#<%= id + 1 %> <%= stat.name %></h3>
      <ul>
        <li><strong><%= number((Map.get(stat, :instances, 0)||0) - (Map.get(stat, :dead_instances, 0)||0), plus: true) %> instances</strong>
          <br /><%= number(Map.get(stat, :instances)) %> new and <%= number(Map.get(stat, :dead_instances)) %> down</li>
        <%= if stat[:users] && stat[:users] > 0 do %><li>New users: <%= number(Map.get(stat, :users)) %></li><% end %>
        <%= if stat[:statuses] && stat[:statuses] > 0 do %><li>New statuses: <%= number(Map.get(stat, :statuses)) %></li><% end %>
      </ul>
    </div>

<% end %>
</div>

<br />
<h3>Declining servers</h3>

<div class="row">
  <%= for {stat, id} <- neg do %>

    <div class="col-sm-4">
      <h3 id="server-<%= stat.slug %>">#<%= id + 1 %> <%= stat.name %></h3>
      <ul>
        <li><strong><%= number((Map.get(stat, :instances, 0)||0) - (Map.get(stat, :dead_instances, 0)||0), plus: true) %> instances</strong>
          <br /><%= number(Map.get(stat, :instances)) %> new and <%= number(Map.get(stat, :dead_instances)) %> down</li>
        <%= if stat[:users] && stat[:users] > 0 do %><li>New users: <%= number(Map.get(stat, :users)) %></li><% end %>
        <%= if stat[:statuses] && stat[:statuses] > 0 do %><li>New statuses: <%= number(Map.get(stat, :statuses)) %></li><% end %>
      </ul>
    </div>

<% end %>
</div>

<br />
<br />
<!--
<h2 id="instances">Instances</h2>

<h3>Biggest new instances</h3>

<h3>Biggest dead instances</h3>

<h3>All time biggest</h3>
-->
<hr />
<small>
  <strong>work in progress -- not completed yet, numbers are a bit wrong</strong>
  <br />
  Data from <%= format_date(@stats.query.from) %> to <%= format_date(@stats.query.to) %> (fediverse.network started crawling on the 23 April)
  <br />
  Counts does not includes instances that have been unreachable since 30 days after the last time period.
  <br />
  Died instances are instances without a successful check since 30 days after the last time period.
  <br />
  Servers are sorted by new instances.
</small>