lib/fd_web/router.ex
defmodule FdWeb.Router do
  use FdWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end


  scope "/", FdWeb do
    pipe_through :browser_auth # Use the default browser stack
    # Manage
    get "/manage", ManageController, :index, as: :manage
    get "/:instance_id/manage", ManageController, :show, as: :manage
    put "/:instance_id/manage", ManageController, :update, as: :manage
    get "/manage/logout", ManageController, :logout
    post "/manage/login", ManageController, :send_token, as: :manage
    get "/manage/login/:token", ManageController, :login_by_token, as: :manage
    get "/tools/nodeinfo", Tools.NodeinfoController, :index, as: :nodeinfo_tool
    post "/tools/nodeinfo", Tools.NodeinfoController, :post, as: :nodeinfo_tool
    get "/tools/nodeinfo/:hostname", Tools.NodeinfoController, :show, as: :nodeinfo_tool
  end

  scope "/", FdWeb do
    pipe_through :browser # Use the default browser stack

    get "/info", PageController, :show
    get "/about", PageController, :show
    get "/about/*slug", PageController, :show
    get "/api/*slug", PageController, :show
    get "/monitoring", PageController, :show
    get "/stats", PageController, :stats

    # Define /pleroma, /mastodon, …
    for s <- Fd.ServerName.list_names do
      get Fd.ServerName.route_path(s), InstanceController, :index, as: :instance_sserver
      get Fd.ServerName.route_path(s) <> "/versions", ServerController, as: :server_sversions
    end

    get "/servers", ServerController, :index

    get "/all", InstanceController, :index, as: :instance_all
    get "/down", InstanceController, :index, as: :instance_down
    get "/newest", InstanceController, :index, as: :instance_newest
    get "/oldest", InstanceController, :index, as: :instance_oldest
    get "/closed", InstanceController, :index, as: :instance_closed
    get "/checks", CheckController, :index, as: :latest_checks
    get "/tld", InstanceController, :tld, as: :instance
    get "/tld/:tld", InstanceController, :index, as: :instance_tld
    get "/domain", InstanceController, :domain, as: :instance
    get "/domain/:domain", InstanceController, :index, as: :instance_domain
    get "/t", InstanceController, :tags, as: :topics
    get "/t/:tag", InstanceController, :index, as: :instance_tag

    get "/hosts", HostController, :index, as: :host

    get "/reports", ReportController, :index
    get "/reports/:report", ReportController, :show


    @traps ~w(wp-login.php)
    for trap <- @traps do
      get "/#{trap}", PageController, :trap
    end

    @notfound ~w(statistics.json siteinfo.json poco)
    for notfound <- @notfound do
      get "/#{notfound}", PageController, :not_found
    end


    resources "/", InstanceController, only: [:index, :show] do
      get "/nodeinfo", InstanceController, :nodeinfo
      get "/stats", InstanceController, :stats
      get "/stats/:interval", InstanceController, :stats
      get "/emojis", InstanceController, :emojis
      get "/peers", InstanceController, :peers
      get "/federation", InstanceController, :federation
      get "/timeline", InstanceController, :timeline
      get "/public_timeline", InstanceController, :public_timeline
      get "/score", InstanceController, :score
      get "/checks", InstanceController, :checks
      get "/checks/:from_time", CheckController, :show, as: :check
      get "/checks/:from_time/:to_time", CheckController, :show, as: :check
      get "/chart/:name", InstanceChartController, :show, as: :chart
    end

    #resources "/tags", TagController

    # This route will mostly never be directly hit (eaten by instance /:id) but this is for route helpers
    # Real routes are generated per-server by Fd.ServerName.list_names a couple of lines before
    get "/:server", InstanceController, :index, as: :instance_server
    get "/:server/versions", ServerController, :versions, as: :server_versions
  end


  if Mix.env == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, [base_path: "/dev/mailbox"]
    end
  end

  scope "/api", FdWeb.Api do
    pipe_through :api
    get "/v1/stats", GlobalStatsController, :index
    get "/v1/stats/server/:server_name", GlobalStatsController, :server
    get "/v1/stats/isps", GlobalStatsController, :isps
    get "/v1/stats/countries", GlobalStatsController, :countries
  end
end

lib/fd/instances/crawler.ex
defmodule Fd.Instances.Crawler do
  @moduledoc """
  # Instance Crawler

  1. Test Masto API (/api/v1/instance)
      1. a. /api/v1/instance/peers (only once per 6h)
      1. b. /api/v1/instance/custom_emojis (only once per 24h)
  2. Test Statusnet API (/api/statusnet/config)
      2. a. /api/statusnet/config
      2. b. Test /main/statistics
  3. Update `Instance`

  Maybe:
    - Could test if we get a reply on /api/z/1.0/channel/stream (so we can know it's hubzilla?)

  """

  # TODO: Store complete crawl state into Instance db

  require Logger
  alias __MODULE__
  alias Fd.{Instances}
  alias Fd.Instances.{Instance, InstanceCheck, Instrumenter}

  defmacro __using__(_) do
    quote do
      alias Fd.Repo
      alias Fd.Instances
      alias Fd.Instances.{Crawler, Instance}
      require Logger
      import Crawler, only: [debug: 2, info: 2, error: 2, request: 2, request: 3], warn: false
    end
  end

  @hackney_pool :hackney_crawler
  @hackney_pool_opts [{:timeout, 50_000}, {:max_connections, 200}, {:connect_timeout, 50_000}]
  @hackney_mon_pool :hackney_crawler_mon
  @hackney_mon_pool_opts [{:timeout, 50_000}, {:max_connections, 100}, {:connect_timeout, 50_000}]
  @hackney_dead_pool :hackney_crawler_dead
  @hackney_dead_pool_opts [{:timeout, 50_000}, {:max_connections, 100}, {:connect_timeout, 150_000}]
  @hackney_opts [{:connect_timeout, 150_000}, {:recv_timeout, 50_000}, {:pool, @hackney_pool}]
  @hackney_mon_opts [{:pool, @hackney_mon_pool}]
  @hackney_dead_opts [{:pool, @hackney_dead_pool}]

  @down_http_codes [301, 410, 502, 503, 504, 505, 520, 521, 522, 523, 524, 525, 526, 527, 530]
  @retry_http_codes [500, 502, 503, 504, 505, 520, 521, 522, 523, 524]
  @nodeinfo_servers ["hubzilla", "Friendica"]
  @nodeinfo_hide_if_not_found_servers ["Friendica"]

  def down_http_codes, do: @down_http_codes
  def nodeinfo_servers, do: @nodeinfo_servers
  def nodeinfo_hide_if_not_found_servers, do: @nodeinfo_hide_if_not_found_servers

  @callback query(t()) :: t()
  @callback process_results(t()) :: t()
  @callback after_run(t()) :: t()

  @pipelines %{
    {"process_results", "final"} => [Crawler.Server, Crawler.Semver, Crawler.PublicSuffix, Crawler.HostInfo,
      Crawler.Changes],
    "after_run" => [Crawler.Server, Crawler.Peers, Crawler.Fedibot, Crawler.MonitoringAlert]
  }

  defstruct [ :instance,
              :halted?,
              :fatal_error,
              :server,

              :has_mastapi?,
              :m_instance,
              :m_peers,
              :m_custom_emojis,

              :has_statusnet?,
              :s_version,
              :s_config,

              :has_peertubeapi?,
              :pt_config,
              :pt_stats,

              :has_nodeinfo?,
              :nodeinfo_schema,
              :nodeinfo,

              :has_misskey?,
              :misskey_meta,
              :misskey_stats,

              :html,

              :changes,
              :check,
              :diffs,
            ]

  @type t :: %__MODULE__{}

  def setup() do
    :ok = :hackney_pool.start_pool(@hackney_pool, @hackney_pool_opts)
    :ok = :hackney_pool.start_pool(@hackney_mon_pool, @hackney_mon_pool_opts)
    :ok = :hackney_pool.start_pool(@hackney_dead_pool, @hackney_dead_pool_opts)
  end

  def put_new(map, key, value) do
    unless Map.get(map, key) do
      put(map, key, value)
    else
      map
    end
  end
  def put(map, key, value) when value in ["", nil] do
    map
  end
  def put(map, key, value) do
    Map.put(map, key, value)
  end

  def run(instance) do
    state = %Crawler{instance: instance, halted?: false, has_mastapi?: false, has_statusnet?: false, has_peertubeapi?:
      false, has_nodeinfo?: false, has_misskey?: false, changes: %{}, check: %{}, diffs: %{}}

    start = :erlang.monotonic_time
    info(state, "starting new crawl")

    # Main pipeline
    state = run_pipeline(state)
    # Final process_results
    mods = Map.get(@pipelines, {"process_results", "final"}, [])
    state = apply_safe_callbacks(state, mods, :process_results)

    pipeline_stop = :erlang.monotonic_time

    changes = Map.get(state, :changes, %{})
              |> Map.put("last_checked_at", DateTime.utc_now())
    state = %Crawler{state | changes: changes}

    debug(state, "changes: #{inspect changes}")

    check_changeset = InstanceCheck.changeset(%InstanceCheck{instance_id: instance.id}, state.check)
    check = Fd.Repo.insert!(check_changeset)
    state = %Crawler{state | check: check}
    state = case Instances.update_instance(instance, state.changes) do
      {:ok, instance} ->

        state = %Crawler{state | instance: instance}

        # After run pipeline
        mods = Map.get(@pipelines, "after_run", [])
        state = apply_safe_callbacks(state, mods, :after_run)

        warn(state, "Checked! #{inspect state.diffs}")
        state
      error ->
        error(state, "FAIL: #{inspect error}")
        state
    end

    finished = :erlang.monotonic_time
    pipeline_duration = pipeline_stop - start
    total_duration = finished - start

    warn(state, "finished in #{:erlang.convert_time_unit(total_duration, :native, :millisecond)}ms (pipeline took #{:erlang.convert_time_unit(pipeline_duration, :native, :millisecond)} ms)!")

    state
  end

  def run_pipeline(state = %{instance: %Instance{server: 2, domain: domain}}) do
    state
    |> query_mastapi_instance()
    |> query_mastapi_peers()
    |> query_mastapi_emojis()
    |> Crawler.Nodeinfo.query()
    |> process_results()
    |> Crawler.Nodeinfo.process_results()
  end

  def run_pipeline(state = %{instance: %Instance{server: 3, domain: domain}}) do
    state
    |> query_mastapi_instance()
    |> query_mastapi_peers()
    |> query_mastapi_emojis()
    |> query_statusnet_config()
    |> Crawler.Nodeinfo.query()
    |> process_results()
    |> Crawler.Nodeinfo.process_results()
  end

  @gnusoc_servers [1, 5, 6]
  def run_pipeline(state = %{instance: %Instance{server: srv, domain: domain}}) when srv in @gnusoc_servers do
    state
    |> query_statusnet_version()
    |> query_statusnet_config()
    |> query_statusnet_config2()
    |> Crawler.Nodeinfo.query()
    |> process_results()
    |> Crawler.Nodeinfo.process_results()
  end

  @nodeinfo_servers [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
    32, 33, 34, 35, 36, 37, 38, 39]
  def run_pipeline(state = %{instance: %Instance{server: srv, domain: domain}}) when srv in @nodeinfo_servers do
    state
    |> Crawler.Nodeinfo.query()
    |> process_results()
    |> Crawler.Nodeinfo.process_results()
  end

  def run_pipeline(state) do
    state
    |> query_mastapi_instance()
    |> query_mastapi_peers()
    |> query_mastapi_emojis()
    |> query_statusnet_version()
    |> query_statusnet_config()
    |> query_peertube_config()
    |> query_peertube_stats()
    |> query_statusnet_config2()
    |> Crawler.Nodeinfo.query()
    |> query_misskey_meta()
    |> query_misskey_stats()
    #|> query_html_index()
    |> process_results()
    |> Crawler.Nodeinfo.process_results()
  end


  def process_results(crawler = %Crawler{halted?: true}) do
    error_s = Fd.HumanError.format(crawler.fatal_error)
    check = %{"up" => false, "error_s" => error_s}

    changes = crawler.changes
    |> Map.put("last_down_at", DateTime.utc_now())
    |> Map.put("up", false)
    %Crawler{crawler | changes: changes, check: check}
  end

  def process_results(crawler = %Crawler{has_mastapi?: true}) do
    changes = %{"last_up_at" => DateTime.utc_now(), "has_mastapi" => true}

    stats = Map.get(crawler.m_instance, "stats", %{})
    {server, version} = Map.get(crawler.m_instance, "version", nil) |> process_mastapi_version()
    user_count = Map.get(stats, "user_count")
    peer_count = Map.get(stats, "domain_count")
    status_count = Map.get(stats, "status_count")
    name = Map.get(crawler.m_instance, "title", crawler.instance.domain)
    description = Map.get(crawler.m_instance, "description")
    email = Map.get(crawler.m_instance, "email")
    emojis = Enum.reduce(crawler.m_custom_emojis || [], %{}, fn
      (%{"url" => url, "shortcode" => code}, emojis) -> Map.put(emojis, code, url)
      (_, emojis) -> emojis
    end)
    emoji_count = Enum.count(emojis)
    max_chars = Map.get(crawler.m_instance, "max_toot_chars", 500)
    contact_account = Map.get(crawler.m_instance, "contact_account", %{})
    registrations = Map.get(crawler.m_instance, "registrations")

    signup = cond do
      registrations == true -> true
      registrations == false -> false
      # FIXME: this was for pleroma but not needed anymore
      crawler.has_statusnet? ->
        if get_in(crawler.s_config, ["site", "closed"]) do
          get_in(crawler.s_config, ["site", "closed"]) == "0"
        else
          nil
        end
      true -> nil
    end

    # gab check
    is_gab = cond do
      name == "Gab Social" -> true
      Enum.member?(Map.keys(contact_account || %{}), "is_pro") && Enum.member?(Map.keys(contact_account || %{}), "is_verified") -> true
      true -> false
    end

    version = if is_gab, do: "#{version}+gab", else: version

    check = %{"up" => true, "users" => user_count, "peers" => peer_count, "statuses" => status_count, "emojis" =>
      emoji_count, "version" => version, "signup" => signup, "max_chars" => max_chars, "server" => Fd.ServerName.to_int(server)}

    changes = changes
    |> Map.put("custom_emojis", emojis)
    |> Map.put("mastapi_instance", crawler.m_instance)
    |> Map.put("statusnet_config", crawler.s_config)
    |> Map.put("server", Fd.ServerName.to_int(server))
    |> Map.put("name", name)
    |> Map.put("description", description)
    |> Map.put("email", email)
    |> Map.put("dead", false)
    |> Map.merge(check)

    %Crawler{crawler | changes: changes, check: check}
  end

  def process_results(crawler = %Crawler{has_peertubeapi?: true}) do
    changes = %{"last_up_at" => DateTime.utc_now()}

lib/fd/instances/crawler/changes.ex
defmodule Fd.Instances.Crawler.Changes do
  use Fd.Instances.Crawler

  def process_results(crawler) do
    last_check = Instances.get_instance_last_check(crawler.instance)
    last_up_check = Instances.get_instance_last_up_check(crawler.instance)

    new? = (last_check == nil)
    is_up? = Map.get(crawler.changes, "up")
    was_up? = (last_check && last_check.up == true)
    became_up? = (is_up? == true && was_up? == false)
    became_down? = (is_up? == false && was_up? == true)
    signup_changed? = if last_up_check && !is_nil(last_up_check.signup) do
      last_up_check.signup != Map.get(crawler.changes, "signup", false)
    else
      false
    end

    version_changed? = if last_up_check && is_up? do
      Map.get(crawler.changes, "version") != last_up_check.version
    else false end
    server_changed? = if last_up_check && is_up? do
      Map.get(crawler.changes, "server", 0) != last_up_check.server
    else false end
    {became_open?, became_closed?} = cond do
      signup_changed? && Map.get(crawler.changes, "signup", true) == false ->
        {false, true}
      signup_changed? && Map.get(crawler.changes, "signup", false) == true ->
        {true, false}
      true ->
        {false, false}
    end

    diffs = %{new?: new?, became_up?: became_up?, became_down?: became_down?, version_changed?: version_changed?,
      server_changed?: server_changed?, is_up?: is_up?, was_up?: was_up?, became_open?: became_open?, became_closed?:
      became_closed?,
      last_up_check: last_up_check
    }
    debug(crawler, "Diffs: " <> inspect(diffs))

    %Crawler{crawler | diffs: diffs}
  end

end

lib/fd/instances/crawler/monitoring_alert.ex
defmodule Fd.Instances.Crawler.MonitoringAlert do
  use Fd.Instances.Crawler

  def after_run(crawler) do
    if Application.get_env(:fd, :monitoring_alerts, false) && crawler.instance.monitor && crawler.instance.settings && crawler.instance.settings.alerts_to_contact do
      spawn(fn() ->
        became_down? = Map.get(crawler.diffs, :became_down, false)
        became_up? = Map.get(crawler.diffs, :became_up, false)
        if became_down? do
          Fd.DownEmail.down_email(crawler.instance, crawler.check)
          |> Fd.Mailer.deliver()
        end
        if became_up? do
          Fd.UpEmail.up_email(crawler.instance)
          |> Fd.Mailer.deliver()
        end
      end)
    end
    crawler
  end

end

lib/fd/instances/crawler/semver.ex
defmodule Fd.Instances.Crawler.Semver do
  use Fd.Instances.Crawler

  def process_results(crawler = %Crawler{changes: changes}) do
    semver = with \
      string when is_binary(string) <- Map.get(changes, "version"),
      {:ok, version} <- Fd.Version.parse(string)
    do
      Fd.Version.to_instance_semver_params(version)
    else
      _ -> nil
    end

    changes = Map.put(changes, "semver", semver)
    %Crawler{crawler | changes: changes}
  end

end

lib/fd_web/templates/instance/index.html.eex
<%= if @filters do %>
  <ul class="filters">
    <li class="filter">
      <strong>Status</strong>
      <ul class="list">
        <li><%= link "Up", to: instance_path(@conn, :index), class: active_class_bool(@filters["up"]=="true") %> 
          <%= display_stat(@stats,:mini, ["instances", "up"]) %></li>
        <li><%= link "Down", to: instance_down_path(@conn, :index), class: active_class_bool(@filters["up"] == "false") %> 
          <%= display_stat(@stats,:mini, ["instances", "down"]) %></li>
        <li><%= link "Newest", to: instance_newest_path(@conn, :index), class: active_class_bool(@filters["age"] == "newest") %>
          <%= display_stat(@stats,:mini, ["instances", "new"]) %></li>
        <li><%= link "Closed", to: instance_closed_path(@conn, :index), class: active_class_bool(@filters["closed"] == "true") %>
          <%= display_stat(@stats,:mini, ["instances", "dead"]) %></li>
        <li><%= link "All", to: instance_all_path(@conn, :index), class: active_class_bool(@filters["up"] == "all" or @filters["up"]==nil) %>
          <%= display_stat(@stats,:mini, ["instances", "alive"]) %></li>
      </ul>
    <li class="filter">
      <strong>Servers</strong>
      <ul class="list">
        <li><%= link "All", to: instance_path(@conn, :index), class: active_class_bool(@filters["server"] == "all" or @filters["server"] == "known") %></li>
        <%= for server = %{hidden: false} <- Fd.ServerName.list() do %>
          <%= unless (get_in(@stats, ["per_server", server.id, "instances", "up"])||0) == 0 do %>
            <li><%= link server.name, to: instance_server_path(@conn, :index, server.path), class: active_class_bool(@filters["server"]==server.path) %> 
              <%= display_stats(@stats,:mini, ["per_server", server.id, "instances"], ["up", "alive"]) %></li>
          <% end %>
        <% end %>
      </ul>
    </li>
  </ul>
  <hr class="my-3"/>

  <%= if data = server_data(@filters["server"]) do %>
    <div class="float-md-right">
      <%= if link = Map.get(data, :source), do: [content_tag(:strong, link("Source code", to: link, class: "btn btn-default")), raw("&nbsp;")] %>
      <%= if link = Map.get(data, :link) do %>
        <%= link(URI.parse(link).host <> " ❯", to: link, class: "btn btn-default") %>
      <% end %>
  </div>
  <% end %>

<h2>
  <%= if(server_data(@filters["server"]), do:
  img_tag("https://static.fediverse.network/icons/servers/#{Map.get(data, :id, "null")}.png?3", style: "max-height:
  42px;max-width:42px;")) %>
  <%= @title %></h2>

<% else %>
  <h2><%= @title %></h2>
<% end %>

<%= if Map.get(@conn.assigns, :tag) do %>
  <%= raw(Earmark.as_html!(@conn.assigns[:tag].description || "")) %>

  <br />
  <p>
    Instances: <%= @stats["instances"] %> - Users: <%= @stats["users"] %> - Statuses: <%= @stats["statuses"] %>
  </p>
<% end %>


<%= if @filters["server"] && @filters["server"]!="known" do %>
<div class="row justify-content-center statistic-rows">
  <% instances = get_in(@stats, ["per_server", Fd.ServerName.to_int(@filters["server"]), "instances", "up"]) %>
  <% instances_total = get_in(@stats, ["instances", "up"]) %>
  <% count = get_in(@stats, ["per_server", Fd.ServerName.to_int(@filters["server"]), "instances", "up"]) %>
  <% percentage = Float.round(percentage(instances_total, instances), 2) %>
  <%= statistic_column("Instances", "#{number(count)} (#{percentage}%)", class: "col") %>

  <% users = get_in(@stats, ["per_server", Fd.ServerName.to_int(@filters["server"]), "users", "up"]) %>
  <% users_total = get_in(@stats, ["users", "up"]) %>
  <% count =  get_in(@stats, ["per_server", Fd.ServerName.to_int(@filters["server"]), "users", "up"]) %>
  <% percentage =  Float.round(percentage(users_total, users), 2) %>
  <%= statistic_column("Users", "#{number(count)} (#{percentage}%)", class: "col") %>
  &nbsp;
  <% statuses = get_in(@stats, ["per_server", Fd.ServerName.to_int(@filters["server"]), "statuses", "up"]) %>
  <% statuses_total = get_in(@stats, ["statuses", "up"]) %>
  <% count = get_in(@stats, ["per_server", Fd.ServerName.to_int(@filters["server"]), "statuses", "up"]) %>
  <% percentage = Float.round(percentage(statuses_total, statuses), 2) %>
  <%= statistic_column("Statuses", "#{number(count)} (#{percentage}%)", class: "col") %>
</div>
<% else %>
  <p>
  Users: <%= display_stat(@stats, :inline, ["users", "up"]) %> - Statuses: <%= display_stat(@stats, :inline, ["statuses", "up"]) %>
</p>
<% end %>

<%= if @filters["server"] && @filters["server"]!="known"  && @filters["up"] == "true"  do %>
  <% s_id = Fd.ServerName.to_int(@filters["server"]) %>
  <% versions = get_in(@stats, ["per_server", s_id, "versions"]) %>
  <% total = get_in(@stats, ["per_server", s_id, "instances", "up"]) %>
  <% percents = Enum.map(versions, fn({version, count}) -> [to_string(version || "?"), count,
    Float.round(percentage(total, count), 2)] end)
  |> Enum.sort_by(fn([version, _, _]) -> version end) %>
  <small>Versions repartition:</small><br />
  <svg class="percent-horizontal-bar"
       data-controller="percent-horizontal-bar"
       data-ts="<%= Jason.encode!(percents) %>"
       data-sort-by="key"
       data-sort-order="desc"
       data-color-scale="sequential"
       data-scheme="PuBuGn"
       >
  </svg>
<% end %>

  <%= server_info(@filters["server"]) %>

<%= if @filters["server"] == "known" && @filters["up"] == "true" do %>
  <% total = get_in(@stats, ["instances", "up"]) %>
  <% per_server = Enum.reduce(Fd.ServerName.list(), [], fn(server, acc) ->
    up = get_in(@stats, ["per_server", server.id, "instances", "up"])
    [ [server.name, up, Float.round(percentage(total, up), 2)] | acc]
  end) %>
  <svg class="percent-horizontal-bar"
       data-controller="percent-horizontal-bar"
       data-ts="<%= Jason.encode!(per_server) %>"
       data-sort-by="value"
       data-sort-order="desc"
       data-color-scale="sequential"
       data-scheme="Rainbow"
       >
  </svg>
<% end %>

<div>
<%= FdWeb.SortFilterView.select_sort(@filters) %>
<table class="table table-condensed table-hover">
  <thead>
    <tr class="">
      <th></th>
      <th>Instance</th>
      <th>Server</th>
      <th>Users</th>
      <th>Statuses</th>
      <th>Peers</th>
      <th>Signup</th>
      <%= if @filters["emojis"] do %>
        <th>Emojis</th>
      <% end %>
      <%= if @filters["age"] do %>
        <th>Age</th>
      <% end %>
      <%= if @filters["max_chars"] do %>
        <th>Max Chars</th>
      <% end %>

    </tr>
  </thead>
  <tbody class="clusterize-content">
    <%= for {instance, idx} <- Enum.with_index(@instances) do %>
    <tr class="">
      <td><span class="badge badge-up-<%= to_string(instance.up) %>">&nbsp;</span></td>
      <td>
        <%= if @filters["statuses"] || @filters["users"], do: [to_string(idx+1), ".", raw("&nbsp;")]%>
        <%= list_instance_name(@conn, instance) %>
        <%= if Enum.any?(instance.tags || [], fn(tag) -> tag.name == "Adult" end) do %>
          &nbsp;<sup title="Adult">🔞</sup>
        <% end %>
        <%= if instance.dead, do: [raw("&nbsp;"), content_tag(:sup, "☨", [title: "Dead"])] %>
      <%= if Fd.Instances.Instance.use_accept_list?(instance), do: [raw("&nbsp;"), content_tag(:sup, raw("&#127763;"),
        [title: "Restricted federation by accept list"])] %>
        <%= if instance.monitor, do: [raw("&nbsp;"), content_tag(:sup, raw("&#128065;"), [title: "Monitored"])] %>
      </td>
      <td><%= Fd.ServerName.fork_name(instance) %> <%= simplify_version(instance.version) %></td>
      <td>
        <%= if instance.users do %>
          <%= chart_tag_lazy(@conn, idx, instance, "users_new.png", [style: "sparkline"], height: 16, width: 50) %>
          &nbsp;
        <% end %>
        <%= instance.users %>
      </td>
      <td >
        <%= if instance.statuses do %>
          <%= chart_tag_lazy(@conn, idx, instance, "statuses_new.png", [style: "sparkline"], height: 16, width: 50) %>
          &nbsp;
        <% end %>
        <%= instance.statuses %>
      </td>
      <td><%= instance.peers %></td>
      <td><%= inspect(instance.signup) %></td>
      <%= if @filters["emojis"] do %>
        <td><%= instance.emojis %></td>
      <% end %>
      <%= if @filters["age"] do %>
        <td><%= instance.inserted_at %></td>
      <% end %>
      <%= if @filters["max_chars"] do %>
        <td><%= instance.max_chars %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
  </table>
</div>
</div>

lib/fd_web/templates/instance/tags.html.eex
<h1>Topics</h1>

<%= for tag <- @tags do %>
  <%= inspect(tag) %>
  <br />
<% end %>